# ======================================================================
# Proteomics Data Analysis Pipeline
# ======================================================================
#
# Project: Comparative Proteome Analyses in Pathogenic Fungi
#
# Description:
# This script contains the analyses of mass spectrometry–based proteomics
# datasets generated by different collaborators, each focusing on distinct
# fungal pathogens, genetic perturbations, and experimental conditions.
#
# ----------------------------------------------------------------------
# Collaborators & Experimental Contexts
# ----------------------------------------------------------------------
#
# 1) Celia Soares
#    Organism: Paracoccidioides brasiliensis
#    Experimental Conditions:
#      - hapX knockdown
#      - zrt knockdown
#      - Recovery after macrophage infection (A549 cell line)
#    Focus:
#      - Iron and zinc homeostasis
#      - Virulence-associated adaptive responses
#      - Host–pathogen interaction
#
# 2) Alexandre Bailão
#    Organism: Histoplasma ohiense (strain G217B)
#    Experimental Conditions:
#      - Ace transcription factor knockdown
#      - Copper stress conditions:
#          * 10 µM Cu
#          * 250 µM Cu
#    Focus:
#      - Copper metabolism
#      - Metal stress response
#      - Transcriptional regulation impacting virulence
#
# 3) Mirelle Bailão
#    Organism: Fonsecaea pedrosoi
#    Experimental Conditions:
#      - Muriform cells (chromoblastomycosis-related morphotype)
#    Focus:
#      - Morphological adaptation
#      - Stress tolerance
#      - Pathogenic differentiation
#
# ----------------------------------------------------------------------
# Analysis Scope:
# - Data import and preprocessing
# - Quality control and normalization
# - Differential protein abundance analysis
# - Functional enrichment (GO / KEGG / custom annotations)
# - Comparative and integrative analyses across conditions
#
# ----------------------------------------------------------------------
# Author: Thalison Rodrigues Moreira
# Program: PhD – Genetics and Molecular Biology
# Institution: Universidade Federal de Goiás (UFG)
#
# Last updated: YYYY-MM-DD
# ======================================================================
